- id: do-not-add-strings
  name: Do not add strings
  description: Forbids commits if any of the specified strings exists.
  language: python
  entry: python check_do_not_add.py
  pass_filenames: false
  exclude: ".pre-commit-config.yaml"