- id: check-forbidden-strings
  name: Check forbidden strings
  description: Forbids commits if any of the specified strings exists.
  language: python
  entry: check_forbidden_strings
  pass_filenames: false
  exclude: ".pre-commit-config.yaml"